/** Trục truyền thông cục bộ: BroadcastChannel + localStorage. */
(function (window) {
    const CHANNEL_NAME = '5c_ai_sync_classroom_channel';
    let channel = null;
    try { if (typeof BroadcastChannel !== 'undefined') channel = new BroadcastChannel(CHANNEL_NAME); } catch (e) { console.warn('BroadcastChannel not available:', e); }
    const LESSON_CONFIGS = {
        bai1:{id:'bai1',title:'Bài 1: Cấu trúc của chất. Sự chuyển thể'}, bai2:{id:'bai2',title:'Bài 2: Nội năng. Định luật I của NĐLH'}, bai3:{id:'bai3',title:'Bài 3: Nhiệt độ. Thang nhiệt độ – nhiệt kế'}, bai4:{id:'bai4',title:'Bài 4: Nhiệt dung riêng'}, bai5:{id:'bai5',title:'Bài 5: Nhiệt nóng chảy riêng (Bài thi GVDG)'}, bai6:{id:'bai6',title:'Bài 6: Nhiệt hoá hơi riêng'}, bai8:{id:'bai8',title:'Bài 8: Mô hình động học phân tử chất khí'}, bai9:{id:'bai9',title:'Bài 9: Định luật Boyle (Đẳng nhiệt)'}, bai10:{id:'bai10',title:'Bài 10: Định luật Charles (Đẳng áp)'}, bai11:{id:'bai11',title:'Bài 11: Phương trình trạng thái khí lí tưởng'}, bai12:{id:'bai12',title:'Bài 12: Áp suất khí & Động năng phân tử'}, bai13:{id:'bai13',title:'Bài 13: Bài tập về khí lí tưởng'}
    };
    const STEPS_CONFIG = {1:{id:1,name:'Bước 1: Khởi động',desc:'Tạo tình huống có vấn đề, phân nhóm và kết nối QR.'},2:{id:2,name:'Bước 2: Tìm tòi',desc:'Thực hiện mô phỏng số và thí nghiệm video để thu thập số liệu.'},3:{id:3,name:'Bước 3: Lập luận',desc:'Phân tích đồ thị, xử lý sai số và đối thoại mở với AI Socrates.'},4:{id:4,name:'Bước 4: Thí nghiệm',desc:'Thực hành ảo, đo đạc thông số thực nghiệm SGK Kết nối tri thức.'},5:{id:5,name:'Bước 5: Áp dụng',desc:'Thi đấu Đấu trường Chuông Vàng và báo cáo sản phẩm nhóm.'}};
    function getMasterState() { try { const raw = localStorage.getItem('master_state_5c_ai'); if (raw) return JSON.parse(raw); } catch (e) {} return {activeLesson:'bai5',currentStep:1,isScreenLocked:false,soundEnabled:true,stageSpotlight:{mode:'default',groupId:1},groupSocratesInteractions:{},timestamp:Date.now()}; }
    function updateMasterState(patch, sender='system') { const updated=Object.assign({},getMasterState(),patch,{lastSender:sender,timestamp:Date.now()}); try{localStorage.setItem('master_state_5c_ai',JSON.stringify(updated));}catch(e){} if(channel)channel.postMessage({type:'MASTER_STATE_UPDATE',state:updated,sender}); return updated; }
    function onMasterStateChange(callback) { if(channel)channel.addEventListener('message',ev=>{if(ev.data?.type==='MASTER_STATE_UPDATE')callback(ev.data.state,ev.data.sender);}); window.addEventListener('storage',ev=>{if(ev.key==='master_state_5c_ai'&&ev.newValue)try{callback(JSON.parse(ev.newValue),'storage_event');}catch(e){}}); }
    function broadcastEvent(eventType,payload={}) { if(channel)channel.postMessage({type:eventType,payload,timestamp:Date.now()}); }
    function setStep(n){n=Math.max(1,Math.min(5,parseInt(n,10)||1));updateMasterState({currentStep:n},'teacher_remote');return n;} function nextStep(){return setStep((parseInt(getMasterState().currentStep,10)||1)+1);} function prevStep(){return setStep((parseInt(getMasterState().currentStep,10)||1)-1);} function toggleScreenLock(){const lock=!getMasterState().isScreenLocked;updateMasterState({isScreenLocked:lock},'teacher_remote');return lock;} function setLesson(id){if(LESSON_CONFIGS[id])updateMasterState({activeLesson:id},'teacher_remote');}
    function toggleFullScreen(){try{const d=document,full=d.fullscreenElement||d.webkitFullscreenElement;if(!full)(d.documentElement.requestFullscreen||d.documentElement.webkitRequestFullscreen)?.call(d.documentElement).catch(console.warn);else(d.exitFullscreen||d.webkitExitFullscreen)?.call(d);}catch(e){console.warn(e);}}
    function setStageSpotlight(mode,groupId=1){const spotlight={mode,groupId,timestamp:Date.now()};updateMasterState({stageSpotlight:spotlight},'teacher_spotlight');return spotlight;}
    function recordGroupQA(groupId,groupName,question,answer){const s=getMasterState(),map=Object.assign({},s.groupSocratesInteractions||{});if(!map[groupId])map[groupId]=[];map[groupId].unshift({id:'qa_'+Date.now(),groupId,groupName,question,answer,time:new Date().toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'}),timestamp:Date.now()});if(map[groupId].length>10)map[groupId].pop();updateMasterState({groupSocratesInteractions:map},'student_qa');return map;}
    window.MASTER_BUS={LESSONS:LESSON_CONFIGS,STEPS:STEPS_CONFIG,getMasterState,updateMasterState,onMasterStateChange,broadcast:broadcastEvent,publish:broadcastEvent,nextStep,prevStep,setStep,toggleScreenLock,setLesson,toggleFullScreen,setStageSpotlight,recordGroupQA};
})(window);
